const icons = {
  DOUBLE_ARCHWAY: '/assets/double-archway.svg',
  DOUBLE_ELLIPSES: '/assets/double-ellipses.svg',
  HORIZONTAL_ELLIPSE: '/assets/horizontal-ellipse.svg',
  FILLED_BACK_TO_TOP: '/assets/filled-back-to-top-arrow.svg',
  FILLED_MEDIUM_ARROW: '/assets/filled-medium-arrow.svg',
  FILLED_LONG_ARROW: '/assets/filled-long-arrow.svg',
  FILLED_LONG_ARROW2: '/assets/filled-long-arrow2.svg',
  FILLED_SPARK: '/assets/filled-spark-for-popup.svg',
  FILLED_SPARK_WHITE: '/assets/filled-spark-white.svg',
  FILLED_LINK: '/assets/filled-link-icon.svg',
  FILLED_SHORT_ARROW: '/assets/filled-short-arrow.svg',
  LONG_FILLED_SPARK_ARROW: '/assets/long-filled-spark-arrow.svg',
  LONG_UNFILLED_SPARK_ARROW: '/assets/long-unfilled-spark-arrow.svg',
  REFINED_SQUIGGLE: '/assets/refined-squiggle.svg',
  SHORT_SQUIGGLE: '/assets/short-squiggle.svg',
  SINGLE_ARCHWAY: '/assets/single-archway.svg',
  SPARK_EXITING_ARCHWAY: 'assets/spark-exiting-archway.svg',
  SQUIGGLE_UNDERLINE: '/assets/squiggle-underline.svg',
  SQUIGGLE_WAVY: '/assets/squiggle-wavy.svg',
  UNFILLED_BACK_TO_TOP: '/assets/unfilled-back-to-top-arrow.svg',
  UNFILLED_LONG_ARROW: '/assets/unfilled-long-arrow.svg',
  UNFILLED_SPARK_WHITE_OUTLINE: '/assets/unfilled-spark-white-outline.svg',
  UNFILLED_LINK: '/assets/unfilled-link-icon.svg',
  UNFILLED_SHORT_ARROW: '/assets/unfilled-short-arrow.svg',
  ALMOST_STRAIGHT_SCRIBBLE: '/assets/almost-straight-scribble.svg',
  X: '/assets/x.svg',
};

export { icons };
